### ISSUE TITLE
--layers_ranks Not used

### ISSUE THREAD

**Issue by typeface-cn** [YupeiLin2388/Exploring-Negatives-in-Contrastive-Learning-for-Unpaired-Image-to-Image-Translation#3]
class PatchNCELoss(nn.Module):
    def __init__(self, opt,patch):

patch Not used

**Comment by YupeiLin2388** [comment]
Thanks for mentioning this!  ` --layers_ranks`  this parameter was used to test the effect of using different numbers of patches for different layers, but it doesn't work on the PUT, so it's not used, we'll update the code later to remove this parameter.
